name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: regtest
      id: regtest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: regtest
        setup-command: pip install -r requirements.txt && pip install pytest-pylint
        command: pytest --pylint
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        REGTEST_RESULTS: "${{steps.regtest.outputs.result}}"
      with:
        runners: regtest
